// ============================================================================
// SemanticAnalyzer.cs - Semantic Analysis Phase
// Poppy Compiler - Multi-system Assembly Compiler
// ============================================================================

using Poppy.Core.Arch;
using Poppy.Core.CodeGen;
using Poppy.Core.Lexer;
using Poppy.Core.Parser;

namespace Poppy.Core.Semantics;

/// <summary>
/// Performs semantic analysis on the AST.
/// </summary>
/// <remarks>
/// The semantic analyzer performs two passes:
/// 1. First pass: Collect all symbol definitions and calculate addresses
/// 2. Second pass: Resolve all symbol references and validate
/// </remarks>
public sealed class SemanticAnalyzer : IAstVisitor<object?> {
	private readonly MacroExpander _macroExpander;
	private readonly List<SemanticError> _errors;
	private readonly List<SemanticWarning> _warnings;
	private bool _targetSetFromSource;
	private int _pass;
	private readonly Dictionary<int, List<(long Start, long End)>> _orgSections = [];
	private long _sectionStart;
	private int _sectionBank;
	private ITargetProfile? _profile;
	private readonly HashSet<long> _autoGeneratedAddresses = [];

	/// <summary>
	/// Gets the symbol table.
	/// </summary>
	public SymbolTable SymbolTable { get; }

	/// <summary>
	/// Gets the current target architecture.
	/// </summary>
	public TargetArchitecture Target { get; private set; }

	/// <summary>
	/// Gets the platform-specific header configuration set by directives.
	/// </summary>
	public IHeaderConfig? HeaderConfig { get; internal set; }

	/// <summary>
	/// Gets the processor state for architectures with flag-dependent operand sizing.
	/// Null for architectures that don't track processor state.
	/// </summary>
	public ProcessorState? ProcessorState { get; private set; }

	/// <summary>
	/// Snapshot of the M/X flags as last declared by an explicit .a8/.a16/.i8/.i16
	/// directive (default: 8-bit). At a label that follows an unconditional
	/// control-flow transfer (rts/rtl/rti/brk/jmp/jml/bra/brl) the linear REP/SEP
	/// inference is meaningless — the label is a jump/return target whose entry
	/// mode cannot be known from fall-through — so the inferred state resets to
	/// this declared snapshot instead of leaking the previous routine's tail mode.
	/// </summary>
	private bool _declaredAccumulator16Bit;
	private bool _declaredIndex16Bit;

	/// <summary>
	/// True when the previous instruction was an unconditional control-flow
	/// transfer; the next label then resets the inferred mode to the declared
	/// snapshot (see <see cref="_declaredAccumulator16Bit"/>).
	/// </summary>
	private bool _modeResetPending;

	/// <summary>
	/// Gets whether the accumulator is in 16-bit mode (65816 M flag clear).
	/// </summary>
	public bool AccumulatorIs16Bit => ProcessorState?.AccumulatorIs16Bit ?? false;

	/// <summary>
	/// Gets whether index registers are in 16-bit mode (65816 X flag clear).
	/// </summary>
	public bool IndexIs16Bit => ProcessorState?.IndexIs16Bit ?? false;

	/// <summary>
	/// Gets all semantic errors.
	/// </summary>
	public IReadOnlyList<SemanticError> Errors => _errors;

	/// <summary>
	/// Gets all semantic warnings.
	/// </summary>
	public IReadOnlyList<SemanticWarning> Warnings => _warnings;

	/// <summary>
	/// Gets whether analysis encountered any errors.
	/// </summary>
	public bool HasErrors => _errors.Count > 0 || _macroExpander.HasErrors;

	/// <summary>
	/// Gets the macro table.
	/// </summary>
	public MacroTable MacroTable { get; }

	/// <summary>
	/// Gets or sets the current address counter.
	/// </summary>
	public long CurrentAddress { get; set; }

	/// <summary>
	/// Gets the current bank number (-1 if not in a bank).
	/// </summary>
	public int CurrentBank { get; private set; } = -1;

	/// <summary>
	/// Gets the configured bank size in bytes.
	/// </summary>
	public int BankSize { get; private set; }

	/// <summary>
	/// Per-bank saved address cursor, keyed by bank number. A `.bank N` with
	/// no following `.org` must resume from wherever bank N's own code last
	/// left off, not silently inherit whatever address some OTHER bank left
	/// `CurrentAddress` at (poppy#390 -- this dictionary didn't exist before,
	/// so `HandleBankDirective` below only ever updated `CurrentBank`,
	/// leaving `CurrentAddress` carrying over the wrong bank's progress and
	/// disagreeing with CodeGenerator's own, differently-wrong reset-to-base
	/// behavior; labels and bytes ended up at two different addresses).
	/// </summary>
	private readonly Dictionary<int, long> _bankCursors = new();

	/// <summary>
	/// Gets or sets whether to auto-generate labels for JSR/JMP targets that don't have a label.
	/// When enabled, creates labels like "sub_8100" for JSR targets and "loc_8200" for JMP targets.
	/// </summary>
	public bool AutoGenerateRoutineLabels { get; set; }

	/// <summary>
	/// Gets the current pass number (1 or 2).
	/// </summary>
	public int Pass => _pass;

	/// <summary>
	/// Adds a semantic error.
	/// </summary>
	/// <param name="message">The error message.</param>
	/// <param name="location">The source location.</param>
	public void AddError(string message, SourceLocation location) {
		_errors.Add(new SemanticError(message, location));
	}

	/// <summary>
	/// Creates a new semantic analyzer.
	/// </summary>
	/// <param name="target">The target architecture.</param>
	public SemanticAnalyzer(TargetArchitecture target = TargetArchitecture.MOS6502) {
		SymbolTable = new SymbolTable();
		MacroTable = new MacroTable();
		_macroExpander = new MacroExpander(MacroTable);
		_errors = [];
		_warnings = [];
		Target = target;
		CurrentAddress = 0;
		_pass = 0;
		_profile = TargetResolver.TryGetProfile(target);
		// Match the code generator (which creates its processor state in its own
		// constructor) so REP/SEP tracking is active even before any target
		// directive (.snes/.lorom/...) is seen in the source (issue #376 case 3).
		ProcessorState = _profile?.CreateProcessorState();
	}

	/// <summary>
	/// Analyzes a program AST.
	/// </summary>
	/// <param name="program">The program to analyze.</param>
	public void Analyze(ProgramNode program) {
		// Pass 0: pre-register EQU/.define constant definitions so the sizing
		// pass (pass 1) resolves forward-referenced constants. Without this,
		// "lda FOO" before "FOO = $43" sizes as Absolute (3 bytes) instead of
		// the emitted ZeroPage (2), drifting every later label by +1 per use
		// (the z80_mem.pasm G8 wild-jump root).
		PreRegisterConstants(program);
		// First pass: collect definitions
		_pass = 1;
		CurrentAddress = 0;
		CurrentBank = -1;
		_bankCursors.Clear();
		_sectionStart = 0;
		_sectionBank = -1;
		_orgSections.Clear();
		ResetModeTracking();
		program.Accept(this);

		// Close the final .org section (collision check for the trailing bytes).
		CloseOrgSection(null);

		// Validate all symbols are defined (skip register names for register-based architectures)
		var profile = Arch.TargetResolver.TryGetProfile(Target);
		Func<string, bool>? builtinCheck = profile is not null
			? name => profile.Encoder.IsRegister(name)
			: null;
		SymbolTable.ValidateAllDefined(builtinCheck);
		_errors.AddRange(SymbolTable.Errors);
		_errors.AddRange(MacroTable.Errors);
		_errors.AddRange(_macroExpander.Errors);

		// Second pass: resolve references
		var macroErrorsBeforePass2 = _macroExpander.Errors.Count;
		_pass = 2;
		CurrentAddress = 0;
		CurrentBank = -1;
		_bankCursors.Clear();
		ResetModeTracking();
		program.Accept(this);

		// Collect any errors from pass 2 (e.g., anonymous label resolution).
		// Macro expansion now runs in both passes, so pass-2 expansion can
		// re-report the same failure (undefined macro, arg count); dedupe by
		// message so the same defect does not print twice.
		_errors.AddRange(SymbolTable.Errors.Skip(_errors.Count));
		for (var i = macroErrorsBeforePass2; i < _macroExpander.Errors.Count; i++) {
			var macroError = _macroExpander.Errors[i];
			if (_errors.All(e => e.Message != macroError.Message)) {
				_errors.Add(macroError);
			}
		}

		// #386: flag the narrow, mechanical branch-over-rep/sep width hazard.
		// Independent of both passes above -- it only reads the already-parsed
		// statement list, not addresses or symbol values.
		DetectBranchOverWidthChangeHazards(program);
	}

	/// <summary>
	/// Poppy#386: M/X width inference is linear over source order, not
	/// control flow. A rep/sep between a conditional branch and its target
	/// label still updates the inferred state used to size the target's own
	/// immediates, even on the branch-taken path that never executed that
	/// rep/sep -- an immediate sized for the wrong width there misaligns
	/// every byte after it (the classic symptom: a phantom BRK a few bytes
	/// later in a disassembly).
	///
	/// Full control-flow analysis is not attempted here (issue #386's own
	/// scope note: "not necessary... a warning covering the narrow,
	/// mechanical case would be enough"). This flags exactly that case: a
	/// conditional branch whose target is reached with a rep/sep textually
	/// between the branch and the label, where the label's own code reaches
	/// a width-dependent immediate before its own explicit .a8/.a16/.i8/.i16
	/// (or its own rep/sep, which re-syncs the same way). It does not
	/// attempt to determine whether the rep/sep "belongs" to a different
	/// conditional path -- Poppy's inference is textual, not path-aware, so
	/// any rep/sep in that range is a real hazard regardless of intent.
	///
	/// Backward branches are skipped: the label there was already visited in
	/// linear order when originally reached, so there is no "skipped" region
	/// between the branch and a label that precedes it.
	/// </summary>
	private void DetectBranchOverWidthChangeHazards(ProgramNode program) {
		if (Target != TargetArchitecture.WDC65816) return;

		var statements = program.Statements;
		var labelIndex = new Dictionary<string, int>(StringComparer.OrdinalIgnoreCase);
		for (var i = 0; i < statements.Count; i++) {
			if (statements[i] is LabelNode label
				&& !IsAnonymousLabelName(label.Name)
				&& !IsNamedAnonymousLabelName(label.Name)) {
				labelIndex[label.Name] = i;
			}
		}

		var warnedStatements = new HashSet<int>();

		for (var i = 0; i < statements.Count; i++) {
			if (statements[i] is not InstructionNode branch) continue;
			if (!IsConditionalBranchMnemonic(branch.Mnemonic)) continue;
			if (branch.Operand is not IdentifierNode target) continue;
			if (!labelIndex.TryGetValue(target.Name, out var labelPos)) continue;
			if (labelPos <= i) continue; // backward branch: not this hazard shape

			var repSepBetween = false;
			for (var j = i + 1; j < labelPos; j++) {
				if (statements[j] is InstructionNode maybeRepSep && IsRepSepMnemonic(maybeRepSep.Mnemonic)) {
					repSepBetween = true;
					break;
				}
			}
			if (!repSepBetween) continue;

			for (var j = labelPos + 1; j < statements.Count; j++) {
				var stmt = statements[j];
				if (stmt is LabelNode) break; // reached the next label -- no hazard here
				if (stmt is DirectiveNode dir && IsWidthDirectiveName(dir.Name)) break; // explicit override
				if (stmt is InstructionNode instr) {
					if (IsRepSepMnemonic(instr.Mnemonic)) break; // re-syncs the width itself
					if (IsWidthDependentImmediate(instr) && warnedStatements.Add(j)) {
						_warnings.Add(new SemanticWarning(
							$"'{target.Name}' is a branch target reached via '{branch.Mnemonic}' " +
							$"(line {branch.Location.Line}) with a rep/sep between the branch and " +
							"this label; the immediate below may be sized for the wrong M/X width " +
							"unless this label opens with an explicit .a8/.a16/.i8/.i16 (or its own " +
							"rep/sep). See poppy#386.",
							stmt.Location));
					}
					break;
				}
			}
		}
	}

	private static bool IsConditionalBranchMnemonic(string mnemonic) => mnemonic.ToLowerInvariant() switch {
		"bcc" or "bcs" or "beq" or "bne" or "bpl" or "bmi" or "bvc" or "bvs" => true,
		_ => false
	};

	private static bool IsRepSepMnemonic(string mnemonic) =>
		mnemonic.Equals("rep", StringComparison.OrdinalIgnoreCase)
		|| mnemonic.Equals("sep", StringComparison.OrdinalIgnoreCase);

	private static bool IsWidthDirectiveName(string name) =>
		name.ToLowerInvariant() is "a8" or "a16" or "i8" or "i16";

	private static bool IsWidthDependentImmediate(InstructionNode instr) {
		if (instr.AddressingMode != AddressingMode.Immediate) return false;
		return instr.Mnemonic.ToLowerInvariant() is
			"lda" or "adc" or "sbc" or "cmp" or "and" or "ora" or "eor" or "bit"
			or "ldx" or "ldy" or "cpx" or "cpy";
	}

	/// <summary>
	/// Pre-registers EQU constant definitions before the sizing pass so
	/// forward-referenced constants (a constant used before its "= expr" line)
	/// still size as the code generator will emit them. Without this the sizing
	/// pass falls back to the parser's Absolute mode for such operands, sizing
	/// them one byte too large and drifting every later label by +1 per use.
	/// Only top-level "=" (equ) definitions are pre-registered: .define is
	/// conditional-aware (.ifdef guards) so it must stay in pass 1's in-order
	/// flow, and definitions whose value references a not-yet-defined constant
	/// are likewise left to pass 1.
	/// </summary>
	private void PreRegisterConstants(ProgramNode program) {
		foreach (var statement in program.Statements) {
			if (statement is not DirectiveNode dir) continue;
			if (!dir.Name.Equals("equ", StringComparison.OrdinalIgnoreCase)) continue;
			if (dir.Arguments.Count < 2 || dir.Arguments[0] is not IdentifierNode id) continue;
			if (SymbolTable.TryGetSymbol(id.Name, out _)) continue;
			var value = EvaluateExpression(dir.Arguments[1]);
			if (value.HasValue) {
				SymbolTable.Define(id.Name, SymbolType.Constant, value, dir.Location);
			}
		}
	}

	/// <inheritdoc />
	public object? VisitProgram(ProgramNode node) {
		foreach (var statement in node.Statements) {
			statement.Accept(this);
		}

		return null;
	}

	/// <inheritdoc />
	public object? VisitLabel(LabelNode node) {
		// A label following an unconditional control-flow transfer is a
		// jump/return target: the linear REP/SEP inference from the previous
		// routine's tail is meaningless there (the mode at the target is set
		// by whatever jumped/called in, not by fall-through). Reset the
		// inferred M/X state to the last explicitly-declared directive state
		// so a handler that does not re-establish its own mode is sized from
		// the declared entry contract instead of the previous routine's tail.
		if (_modeResetPending && ProcessorState is not null) {
			ProcessorState.AccumulatorIs16Bit = _declaredAccumulator16Bit;
			ProcessorState.IndexIs16Bit = _declaredIndex16Bit;
			_modeResetPending = false;
		}

		if (_pass == 1) {
			// Handle anonymous labels (+ or -)
			if (IsAnonymousLabelName(node.Name)) {
				bool isForward = node.Name[0] == '+';
				SymbolTable.DefineAnonymousLabel(isForward, CurrentAddress, node.Location);
			} else if (IsNamedAnonymousLabelName(node.Name)) {
				// Named anonymous labels (+name)
				SymbolTable.DefineNamedAnonymousLabel(node.Name, CurrentAddress, node.Location);
			} else {
				var symbol = SymbolTable.Define(
					node.Name,
					SymbolType.Label,
					CurrentAddress,
					node.Location);
				// Record the bank so cross-bank long references (jml/jsl/.dl)
				// can encode the label's bank byte
				symbol.Bank = CurrentBank;
			}
		}

		return null;
	}

	/// <summary>
	/// Checks if a name represents an anonymous label (all + or all -).
	/// </summary>
	private static bool IsAnonymousLabelName(string name) {
		if (string.IsNullOrEmpty(name)) return false;
		char first = name[0];
		if (first != '+' && first != '-') return false;
		return name.All(c => c == first);
	}

	/// <summary>
	/// Checks if a name represents a named anonymous label (+name or -name).
	/// </summary>
	private static bool IsNamedAnonymousLabelName(string name) {
		if (string.IsNullOrEmpty(name) || name.Length < 2) return false;
		char first = name[0];
		if (first != '+' && first != '-') return false;
		// Must have identifier characters after the prefix
		return char.IsLetter(name[1]) || name[1] == '_';
	}

	/// <inheritdoc />
	public object? VisitInstruction(InstructionNode node) {
		// Visit all operands to resolve symbols
		foreach (var operand in node.Operands) {
			operand.Accept(this);
		}

		// Auto-generate labels for JSR/JMP targets in pass 1
		if (AutoGenerateRoutineLabels && _pass == 1) {
			TryAutoGenerateLabel(node);
		}

		// Track REP/SEP instructions for M/X flag state (65816)
		if (Target == TargetArchitecture.WDC65816) {
			TrackRepSep(node);
		}

		// A return instruction (rts/rtl/rti/brk) ends the linear fall-through:
		// the next label is an EXTERNAL entry point (jumped/called in from
		// somewhere else), so the inferred mode must reset there to the
		// declared directive state (handled in VisitLabel). jmp/jml/bra/brl
		// deliberately do NOT trigger this: their targets are commonly
		// same-routine continuation labels reached with the linear mode
		// (e.g. the dispatch's `jmp ($C81B,x)` followed by `dispatch_cb:`
		// which is entered via `beq dispatch_cb` in 16-bit mode). The flag is
		// never cleared by a non-return instruction: anything between the
		// return and the next label is unreachable dead code, and the label
		// is still an entry point.
		if (IsReturnInstruction(node.Mnemonic)) {
			_modeResetPending = true;
		}

		// Resolve effective addressing mode for sizing (match code generator's optimizations)
		// Only optimize for operands with known constant values to avoid interfering
		// with anonymous label resolution or forward reference tracking.
		var effectiveMode = node.AddressingMode;
		if (node.Operand is not null) {
			var value = TryGetConstantOperandValue(node.Operand);
			if (value.HasValue) {
				effectiveMode = ResolveEffectiveSizingMode(node.Mnemonic, effectiveMode, value.Value);

				// A 24-bit memory operand must fit the resolved encoding; the
				// code generator fails the same way. Without this, the layout
				// pass would size e.g. 65816 "sta abs,y" and let the bank byte
				// vanish silently (issue #379).
				if (_pass == 1 && value.Value > 0xffff
					&& effectiveMode is not (AddressingMode.AbsoluteLong or AddressingMode.AbsoluteLongX)
					&& effectiveMode != AddressingMode.Immediate) {
					_errors.Add(new SemanticError(
						$"Operand ${value.Value:X6} does not fit the {effectiveMode} encoding; the instruction has no long form for this mode",
						node.Location));
				}
			}
		}

		// Calculate instruction size
		var size = GetInstructionSize(node, effectiveMode);
		CurrentAddress += size;

		return null;
	}

	/// <summary>
	/// Returns true for 65816 instructions that unconditionally end the linear
	/// fall-through and transfer control to an external/call site: rts, rtl,
	/// rti, brk. jmp/jml/bra/brl are deliberately excluded (same-routine
	/// continuation targets keep the linear mode inference).
	/// </summary>
	private static bool IsReturnInstruction(string mnemonic) {
		return mnemonic.Equals("rts", StringComparison.OrdinalIgnoreCase)
			|| mnemonic.Equals("rtl", StringComparison.OrdinalIgnoreCase)
			|| mnemonic.Equals("rti", StringComparison.OrdinalIgnoreCase)
			|| mnemonic.Equals("brk", StringComparison.OrdinalIgnoreCase);
	}

	/// <summary>
	/// Resets the inferred M/X state to the profile default and clears the
	/// declared snapshot and pending-reset flag. Called at the start of every
	/// pass so pass 2 sizes identically to pass 1 (a stale tail mode from the
	/// end of pass 1 would otherwise leak into the beginning of pass 2).
	/// </summary>
	private void ResetModeTracking() {
		ProcessorState = _profile?.CreateProcessorState();
		_declaredAccumulator16Bit = false;
		_declaredIndex16Bit = false;
		_modeResetPending = false;
	}

	/// <summary>
	/// Tracks REP/SEP instructions to update M/X flag state via the target profile.
	/// </summary>
	private void TrackRepSep(InstructionNode node) {
		if (ProcessorState is null || _profile is null) return;

		if (!node.Mnemonic.Equals("rep", StringComparison.OrdinalIgnoreCase) &&
			!node.Mnemonic.Equals("sep", StringComparison.OrdinalIgnoreCase)) return;

		// Try to evaluate the operand to get the flag bits
		if (node.Operand is null) return;
		var value = EvaluateExpression(node.Operand);
		if (!value.HasValue) return;

		_profile.UpdateProcessorFlags(node.Mnemonic.ToLowerInvariant(), value, ProcessorState);
	}

	/// <summary>
	/// Tries to auto-generate a label for JSR/JMP instructions targeting unlabeled addresses.
	/// </summary>
	private void TryAutoGenerateLabel(InstructionNode node) {
		// Only handle JSR and JMP instructions with absolute addressing
		if ((!node.Mnemonic.Equals("jsr", StringComparison.OrdinalIgnoreCase) &&
			!node.Mnemonic.Equals("jmp", StringComparison.OrdinalIgnoreCase)) ||
			node.AddressingMode is not (AddressingMode.Absolute or AddressingMode.ZeroPage)) {
			return;
		}

		// Check if the operand is a literal number (not a symbol reference)
		if (node.Operand is not NumberLiteralNode numberNode) {
			return;
		}

		var targetAddress = numberNode.Value;

		// Don't generate duplicate labels for the same address
		if (_autoGeneratedAddresses.Contains(targetAddress)) {
			return;
		}

		// Check if there's already a label at this address
		if (HasLabelAtAddress(targetAddress)) {
			return;
		}

		// Generate the label name
		var prefix = node.Mnemonic.Equals("jsr", StringComparison.OrdinalIgnoreCase) ? "sub" : "loc";
		var labelName = $"{prefix}_{targetAddress:x4}";

		// Make sure the label name doesn't conflict with an existing symbol
		if (SymbolTable.Symbols.ContainsKey(labelName)) {
			return;
		}

		// Define the auto-generated label
		SymbolTable.Define(labelName, SymbolType.Label, targetAddress, node.Location);
		_autoGeneratedAddresses.Add(targetAddress);
	}

	/// <summary>
	/// Checks if any label is defined at the specified address.
	/// </summary>
	private bool HasLabelAtAddress(long address) {
		return SymbolTable.Symbols.Values.Any(s =>
			s.Type == SymbolType.Label &&
			s.Value.HasValue &&
			s.Value.Value == address);
	}

	/// <summary>
	/// Checks if an instruction is a branch instruction (uses relative addressing).
	/// </summary>
	private bool IsBranchInstruction(string mnemonic) {
		var lower = mnemonic.ToLowerInvariant();

		// Standard 6502/65816 branches
		if (lower is "bcc" or "bcs" or "beq" or "bmi" or "bne" or "bpl" or "bvc" or "bvs" or "bra") {
			return true;
		}

		// Architecture-specific branch detection (e.g., V30MZ conditional jumps/loops)
		var branchProfile = Arch.TargetResolver.TryGetProfile(Target);
		if (branchProfile is not null && branchProfile.Encoder.IsBranchInstruction(lower)) {
			return true;
		}

		return false;
	}

	/// <summary>
	/// Checks if an instruction is a long (16-bit offset) relative branch.
	/// </summary>
	private bool IsLongBranchInstruction(string mnemonic) {
		var branchProfile = Arch.TargetResolver.TryGetProfile(Target);
		return branchProfile is not null && branchProfile.Encoder.IsLongBranchInstruction(mnemonic);
	}

	/// <inheritdoc />
	public object? VisitDirective(DirectiveNode node) {
		switch (node.Name.ToLowerInvariant()) {
			case "org":
				HandleOrgDirective(node);
				break;

			case "equ":
			case "=":
				HandleEquDirective(node);
				break;

			case "byte":
			case "db":
				HandleDataDirective(node, 1);
				break;

			case "word":
			case "dw":
				HandleDataDirective(node, 2);
				break;

			case "long":
			case "dl":
			case "dd":
				HandleDataDirective(node, Target == TargetArchitecture.WDC65816 ? 3 : 4);
				break;

			case "ds":
			case "fill":
			case "res":
				HandleSpaceDirective(node);
				break;

			case "incbin":
				HandleIncbinDirective(node);
				break;

			case "define":
				HandleDefineDirective(node);
				break;

			// Target directives
			case "target":
				HandleTargetDirective(node);
				break;

			case "nes":
				SetTarget(TargetArchitecture.MOS6502, node);
				break;

			case "snes":
				SetTarget(TargetArchitecture.WDC65816, node);
				break;

			case "gb":
			case "gameboy":
				SetTarget(TargetArchitecture.SM83, node);
				break;

			case "channelf":
			case "channel-f":
			case "f8":
				SetTarget(TargetArchitecture.F8, node);
				break;

			case "gba":
			case "gameboyadvance":
				SetTarget(TargetArchitecture.ARM7TDMI, node);
				break;

			case "spc700":
			case "spc":
				SetTarget(TargetArchitecture.SPC700, node);
				break;

			// SNES memory mapping
			case "lorom":
			case "hirom":
			case "exhirom":
				if (_profile?.TryHandleDirective(node, this) != true) {
					AddError($".{node.Name.ToLowerInvariant()} directive is only valid for SNES/65816 target", node.Location);
				}
				break;

			// 65816 register size directives
			case "a8":
			case "a16":
			case "i8":
			case "i16":
			case "smart":
				if (ProcessorState is not null) {
					_profile?.TryHandleProcessorDirective(node.Name.ToLowerInvariant(), ProcessorState);
					// Snapshot the declared entry state so labels following a
					// return instruction reset to it instead of leaking the
					// previous routine's tail mode.
					_declaredAccumulator16Bit = ProcessorState.AccumulatorIs16Bit;
					_declaredIndex16Bit = ProcessorState.IndexIs16Bit;
				}
				break;

			// NES mapper
			case "mapper":
			// iNES header directives
			case "ines_prg":
			case "ines_chr":
			case "ines_mapper":
			case "ines_submapper":
			case "ines_mirroring":
			case "ines_battery":
			case "ines_trainer":
			case "ines_fourscreen":
			case "ines_prgram":
			case "ines_chrram":
			case "ines_pal":
			case "ines2":
				if (_profile?.TryHandleDirective(node, this) != true) {
					AddError($".{node.Name.ToLowerInvariant()} directive is only valid for NES/6502 target", node.Location);
				}
				break;

			// SNES header directives
			case "snes_title":
			case "snes_region":
			case "snes_version":
			case "snes_rom_size":
			case "snes_ram_size":
			case "snes_fastrom":
				if (_profile?.TryHandleDirective(node, this) != true) {
					AddError($".{node.Name.ToLowerInvariant()} directive is only valid for SNES/65816 target", node.Location);
				}
				break;

			// Game Boy header directives
			case "gb_title":
			case "gb_cgb":
			case "gb_sgb":
			case "gb_cartridge_type":
			case "gb_rom_size":
			case "gb_ram_size":
			case "gb_region":
			case "gb_version":
				if (_profile?.TryHandleDirective(node, this) != true) {
					AddError($".{node.Name.ToLowerInvariant()} directive is only valid for Game Boy/SM83 target", node.Location);
				}
				break;

			// Atari Lynx header/boot directives
			case "lynx_name":
			case "lynx_manufacturer":
			case "lynx_rotation":
			case "lynx_bank0_size":
			case "lynx_bank1_size":
			case "lynxentry":
			case "lynxboot":
				if (_profile?.TryHandleDirective(node, this) != true) {
					AddError($".{node.Name.ToLowerInvariant()} directive is only valid for Atari Lynx/65SC02 target", node.Location);
				}
				break;

			// GBA header directives
			case "gba_title":
			case "gba_game_code":
			case "gba_maker_code":
			case "gba_version":
			case "gba_entry":
				if (_profile?.TryHandleDirective(node, this) != true) {
					AddError($".{node.Name.ToLowerInvariant()} directive is only valid for GBA/ARM7TDMI target", node.Location);
				}
				break;

			// SPC700 file directives
			case "spc_song_title":
			case "spc_game_title":
			case "spc_artist":
			case "spc_entry":
				if (_profile?.TryHandleDirective(node, this) != true) {
					AddError($".{node.Name.ToLowerInvariant()} directive is only valid for SPC700 target", node.Location);
				}
				break;

			// Assertions and diagnostics
			case "assert":
				HandleAssertDirective(node);
				break;

			case "error":
				HandleErrorDirective(node);
				break;

			case "warning":
				HandleWarningDirective(node);
				break;

			case "bank":
				HandleBankDirective(node);
				break;

			case "banksize":
				HandleBanksizeDirective(node);
				break;

			default:
				// Visit arguments for symbol resolution
				foreach (var arg in node.Arguments) {
					arg.Accept(this);
				}

				break;
		}

		return null;
	}

	/// <inheritdoc />
	public object? VisitExpression(ExpressionNode node) {
		// Base expression - should not be called directly
		return null;
	}

	/// <inheritdoc />
	public object? VisitBinaryExpression(BinaryExpressionNode node) {
		node.Left.Accept(this);
		node.Right.Accept(this);
		return null;
	}

	/// <inheritdoc />
	public object? VisitUnaryExpression(UnaryExpressionNode node) {
		node.Operand.Accept(this);
		return null;
	}

	/// <inheritdoc />
	public object? VisitNumberLiteral(NumberLiteralNode node) {
		return node.Value;
	}

	/// <inheritdoc />
	public object? VisitStringLiteral(StringLiteralNode node) {
		return node.Value;
	}

	/// <inheritdoc />
	public object? VisitIdentifier(IdentifierNode node) {
		// Handle special identifiers
		if (node.Name == "*" || node.Name == "$") {
			return CurrentAddress;
		}

		// Handle anonymous label references (+ or -) only in pass 2
		if (IsAnonymousLabelName(node.Name)) {
			if (_pass == 2) {
				bool isForward = node.Name[0] == '+';
				int count = node.Name.Length;
				var address = SymbolTable.ResolveAnonymousLabel(isForward, count, CurrentAddress, node.Location);
				return address;
			}

			return null;
		}

		// Handle named anonymous label references (+name or -name) only in pass 2
		if (IsNamedAnonymousLabelName(node.Name)) {
			if (_pass == 2) {
				var address = SymbolTable.ResolveNamedAnonymousLabel(node.Name, CurrentAddress, node.Location);
				return address;
			}

			return null;
		}

		// Reference the symbol
		SymbolTable.Reference(node.Name, node.Location);
		return null;
	}

	/// <inheritdoc />
	public object? VisitMacroDefinition(MacroDefinitionNode node) {
		if (_pass == 1) {
			// Parameters are already MacroParameter objects (from the parser)
			var parameters = node.Parameters.ToList();

			// Store the macro body as statements
			var body = node.Body.ToList();

			// Define the macro in the macro table
			MacroTable.Define(node.Name, parameters, body, node.Location);

			// Also add to symbol table for reference tracking
			SymbolTable.Define(
				node.Name,
				SymbolType.Macro,
				null,
				node.Location);
		}

		return null;
	}

	/// <inheritdoc />
	public object? VisitMacroInvocation(MacroInvocationNode node) {
		// Reference the macro
		SymbolTable.Reference(node.Name, node.Location);

		// Visit arguments
		foreach (var arg in node.Arguments) {
			arg.Accept(this);
		}

		// Expand in BOTH passes: the code generator expands unconditionally, so
		// pass 1 must also advance CurrentAddress past the expanded body or
		// every label after a macro invocation gets a stale address (issue #380
		// case 3). Argument expressions are substituted structurally and only
		// evaluated when the expanded statements are visited, so forward
		// references behave like source-level code.
		var expandedStatements = _macroExpander.Expand(node, node.Arguments);

		// Visit each expanded statement
		foreach (var statement in expandedStatements) {
			statement.Accept(this);
		}

		return null;
	}

	/// <inheritdoc />
	public object? VisitConditional(ConditionalNode node) {
		// Evaluate the condition
		// For symbol conditionals (.ifdef/.ifndef), null means symbol is not defined (treat as 0)
		var conditionValue = EvaluateConditionalExpression(node.Condition);

		// Determine which block to execute
		if (conditionValue != 0) {
			// Execute the then block
			foreach (var statement in node.ThenBlock) {
				statement.Accept(this);
			}
		} else {
			// Try elseif branches
			bool executed = false;
			foreach (var (condition, block) in node.ElseIfBranches) {
				var elseIfValue = EvaluateConditionalExpression(condition);
				if (elseIfValue != 0) {
					foreach (var statement in block) {
						statement.Accept(this);
					}

					executed = true;
					break;
				}
			}

			// Execute else block if no conditions were true
			if (!executed && node.ElseBlock is not null) {
				foreach (var statement in node.ElseBlock) {
					statement.Accept(this);
				}
			}
		}

		return null;
	}

	/// <summary>
	/// Evaluates a conditional expression, treating null (undefined symbol) as 0.
	/// Used by code generator for conditional assembly.
	/// </summary>
	public long EvaluateConditionalExpression(ExpressionNode expr) {
		// Special handling for logical NOT of identifier (.ifndef)
		// This must come before the general identifier handling
		if (expr is UnaryExpressionNode { Operator: UnaryOperator.LogicalNot, Operand: IdentifierNode identifier }) {
			// For .ifndef: return 1 if NOT defined, 0 if defined
			return SymbolTable.TryGetSymbol(identifier.Name, out var symbol) && symbol is not null ? 0 : 1;
		}

		// For normal expressions (including bare identifiers), evaluate the value
		// This handles both `.if SYMBOL` (evaluates symbol's value) and `.if expr`
		return EvaluateExpression(expr) ?? 0;
	}

	/// <inheritdoc />
	public object? VisitRepeatBlock(RepeatBlockNode node) {
		// Evaluate the repeat count
		var count = EvaluateExpression(node.Count);

		if (!count.HasValue || count.Value < 0) {
			_errors.Add(new SemanticError(
				$"Invalid repeat count: {count?.ToString() ?? "null"}",
				node.Location));
			return null;
		}

		// Execute the body count times
		for (int i = 0; i < count.Value; i++) {
			foreach (var statement in node.Body) {
				statement.Accept(this);
			}
		}

		return null;
	}

	/// <inheritdoc />
	public object? VisitEnumerationBlock(EnumerationBlockNode node) {
		// Only define symbols in pass 1
		if (_pass != 1) return null;

		// Evaluate the starting value
		var currentValue = EvaluateExpression(node.StartValue);
		if (!currentValue.HasValue) {
			_errors.Add(new SemanticError(
				"Enumeration start value must be a constant expression",
				node.Location));
			return null;
		}

		// Process each member
		var value = currentValue.Value;
		foreach (var member in node.Members) {
			// If member has explicit value, use it
			if (member.Value is not null) {
				var explicitValue = EvaluateExpression(member.Value);
				if (!explicitValue.HasValue) {
					_errors.Add(new SemanticError(
						$"Enumeration member '{member.Name}' value must be a constant expression",
						node.Location));
					continue;
				}

				value = explicitValue.Value;
			}

			// Define the symbol with current value
			SymbolTable.Define(member.Name, SymbolType.Constant, value, node.Location);

			// Auto-increment based on size directive
			var incrementSize = member.SizeDirective switch {
				".db" => 1,
				".dw" => 2,
				".dl" => 3,
				_ => 1
			};
			value += incrementSize;
		}

		return null;
	}

	// ========================================================================
	// Directive Handlers
	// ========================================================================

	/// <summary>
	/// Handles .org directive to set the current address.
	/// </summary>
	private void HandleOrgDirective(DirectiveNode node) {
		if (node.Arguments.Count < 1) {
			_errors.Add(new SemanticError(
				".org directive requires an address argument",
				node.Location));
			return;
		}

		var value = EvaluateExpression(node.Arguments[0]);
		if (value.HasValue) {
			// Close the section that just ended and detect byte-range
			// collisions with earlier sections (issue #377). Only pass 1
			// reports; pass 2 re-walks for forward-reference resolution.
			if (_pass == 1) {
				CloseOrgSection(node);
			}

			// 24-bit .org on banked targets (e.g., SNES LoROM $018000):
			// set the current bank and bank-local address consistently
			if (_profile is not null
				&& _profile.TryDecomposeBankedAddress(value.Value, out var bank, out var offset)) {
				CurrentBank = bank;
				CurrentAddress = offset;
			} else {
				CurrentAddress = value.Value;
			}

			if (_pass == 1) {
				_sectionStart = CurrentAddress;
				_sectionBank = CurrentBank;
			}
		}
	}

	/// <summary>
	/// Closes the current .org section and verifies its byte range does not
	/// overlap bytes already emitted by an earlier section in the same bank.
	/// Later .org sections may land in earlier gaps (forward-then-backward
	/// layouts), so this checks filled intervals rather than a high-water mark.
	/// </summary>
	private void CloseOrgSection(DirectiveNode? node) {
		var end = CurrentAddress;
		var start = _sectionStart;
		var bank = _sectionBank;

		// Empty section (immediately adjacent .org directives) cannot overlap.
		if (end <= start) {
			return;
		}

		if (!_orgSections.TryGetValue(bank, out var list)) {
			list = [];
			_orgSections[bank] = list;
		}

		foreach (var (s, e) in list) {
			// Intervals [start,end) and [s,e) overlap iff start < e && s < end.
			if (start < e && s < end) {
				_errors.Add(new SemanticError(
					$".org section at ${start:X4}-${end:X4} (bank {(bank < 0 ? "n/a" : bank.ToString("X2"))}) overlaps previously emitted bytes at ${s:X4}-${e:X4}",
					node?.Location ?? default));
				break;
			}
		}

		list.Add((start, end));
	}

	/// <summary>
	/// Handles .bank N directive to set the current bank number.
	/// </summary>
	private void HandleBankDirective(DirectiveNode node) {
		if (node.Arguments.Count < 1) {
			_errors.Add(new SemanticError(
				".bank directive requires a bank number",
				node.Location));
			return;
		}

		var value = EvaluateExpression(node.Arguments[0]);
		if (!value.HasValue) {
			_errors.Add(new SemanticError(
				"Cannot evaluate .bank argument",
				node.Location));
			return;
		}

		var bankNumber = (int)value.Value;
		if (bankNumber < 0) {
			_errors.Add(new SemanticError(
				$"Bank number cannot be negative: {bankNumber}",
				node.Location));
			return;
		}

		// Save the OUTGOING bank's cursor before switching away from it
		// (poppy#390 -- see the _bankCursors field comment above;
		// CodeGenerator.HandleBankDirective mirrors this exact logic so
		// labels, assigned here in the analysis pass, land at the same
		// address CodeGenerator later places that instruction's bytes at).
		if (CurrentBank >= 0) {
			_bankCursors[CurrentBank] = CurrentAddress;
		}

		CurrentBank = bankNumber;

		// Resume this bank's own previously-saved cursor if it has one;
		// otherwise (first visit to this bank) default to the bank's CPU
		// base, same as CodeGenerator does. Profiles with no banked CPU
		// window (GetBankCpuBase returns -1) leave CurrentAddress untouched,
		// same as before this fix -- `.bank` alone never affected address
		// tracking for those targets and still doesn't.
		if (_bankCursors.TryGetValue(bankNumber, out var savedAddress)) {
			CurrentAddress = savedAddress;
		} else {
			var cpuBase = _profile?.GetBankCpuBase(bankNumber) ?? -1;
			if (cpuBase >= 0) {
				CurrentAddress = cpuBase;
			}
		}
	}

	/// <summary>
	/// Handles .banksize N directive to set the bank size in bytes.
	/// </summary>
	private void HandleBanksizeDirective(DirectiveNode node) {
		if (node.Arguments.Count < 1) {
			_errors.Add(new SemanticError(
				".banksize directive requires a size argument",
				node.Location));
			return;
		}

		var value = EvaluateExpression(node.Arguments[0]);
		if (value.HasValue && value.Value > 0) {
			BankSize = (int)value.Value;
		} else {
			_errors.Add(new SemanticError(
				".banksize must be a positive integer",
				node.Location));
		}
	}

	/// <summary>
	/// Handles .equ or = directive to define a constant.
	/// </summary>
	private void HandleEquDirective(DirectiveNode node) {
		if (_pass != 1) return;

		if (node.Arguments.Count < 2) {
			_errors.Add(new SemanticError(
				".equ directive requires a name and value",
				node.Location));
			return;
		}

		if (node.Arguments[0] is not IdentifierNode nameNode) {
			_errors.Add(new SemanticError(
				".equ directive requires an identifier as the first argument",
				node.Location));
			return;
		}

		var value = EvaluateExpression(node.Arguments[1]);
		// Constants pre-registered by the forward-reference pre-pass are
		// already defined with their value; re-defining here would raise the
		// duplicate-symbol error.
		if (SymbolTable.TryGetSymbol(nameNode.Name, out var existing)
			&& existing is not null && existing.IsDefined && existing.Type == SymbolType.Constant) {
			return;
		}
		SymbolTable.Define(nameNode.Name, SymbolType.Constant, value, node.Location);
	}

	/// <summary>
	/// Handles data directives (.byte, .word, etc.).
	/// </summary>
	private void HandleDataDirective(DirectiveNode node, int bytesPerElement) {
		foreach (var arg in node.Arguments) {
			if (arg is StringLiteralNode strNode) {
				// Each character is one byte
				CurrentAddress += strNode.Value.Length;
			} else {
				arg.Accept(this);
				CurrentAddress += bytesPerElement;
			}
		}
	}

	/// <summary>
	/// Handles space/reserve directives (.ds, .fill, .res).
	/// </summary>
	private void HandleSpaceDirective(DirectiveNode node) {
		if (node.Arguments.Count < 1) {
			_errors.Add(new SemanticError(
				$".{node.Name} directive requires a count argument",
				node.Location));
			return;
		}

		var count = EvaluateExpression(node.Arguments[0]);
		if (count.HasValue) {
			CurrentAddress += count.Value;
		}
	}

	/// <summary>
	/// Handles .incbin during the layout pass: advances the address counter by the
	/// number of bytes the code generator will emit for this file, so that every
	/// symbol defined after an .incbin gets its real address. Any problem with the
	/// file itself (missing, unreadable, bad offset/length) is left for the code
	/// generator to report, so it is diagnosed exactly once.
	/// </summary>
	private void HandleIncbinDirective(DirectiveNode node) {
		if (node.Arguments.Count < 1 || node.Arguments[0] is not StringLiteralNode filenameNode) {
			return;
		}

		// Resolve relative to the source file, matching CodeGenerator.HandleIncbinDirective.
		var basePath = Path.GetDirectoryName(node.Location.FilePath) ?? ".";
		var fullPath = Path.Combine(basePath, filenameNode.Value);

		long fileLength;
		try {
			var info = new FileInfo(fullPath);
			if (!info.Exists) {
				return;
			}

			fileLength = info.Length;
		} catch (Exception) {
			return;
		}

		long offset = 0;
		long length = fileLength;

		if (node.Arguments.Count >= 2) {
			var offsetValue = EvaluateExpression(node.Arguments[1]);
			if (offsetValue.HasValue) {
				offset = offsetValue.Value;
			}
		}

		if (node.Arguments.Count >= 3) {
			var lengthValue = EvaluateExpression(node.Arguments[2]);
			if (lengthValue.HasValue) {
				length = lengthValue.Value;
			}
		}

		// Out-of-range offset/length emits nothing; the generator reports the error.
		if (offset < 0 || offset >= fileLength || length < 0 || offset + length > fileLength) {
			return;
		}

		CurrentAddress += length;
	}

	/// <summary>
	/// Handles .define directive.
	/// </summary>
	private void HandleDefineDirective(DirectiveNode node) {
		if (_pass != 1) return;

		if (node.Arguments.Count < 1) {
			_errors.Add(new SemanticError(
				".define directive requires at least a name",
				node.Location));
			return;
		}

		if (node.Arguments[0] is not IdentifierNode nameNode) {
			_errors.Add(new SemanticError(
				".define directive requires an identifier",
				node.Location));
			return;
		}

		long? value = null;
		if (node.Arguments.Count >= 2) {
			value = EvaluateExpression(node.Arguments[1]);
		}

		SymbolTable.Define(nameNode.Name, SymbolType.Constant, value ?? 1, node.Location);
	}

	/// <summary>
	/// Handles .target directive with architecture argument.
	/// </summary>
	private void HandleTargetDirective(DirectiveNode node) {
		if (_pass != 1) return;

		if (node.Arguments.Count < 1) {
			_errors.Add(new SemanticError(
				".target directive requires an architecture (nes, snes, gb, atari2600, lynx, genesis, sms, ws, gba, spc700, tg16, channelf)",
				node.Location));
			return;
		}

		// Accept both identifiers (e.g., "nes") and numeric literals (e.g., 6502, 65816)
		// since common CPU names like 6502, 6507, 2600, 65816, 68000 are registered aliases
		string targetName;
		if (node.Arguments[0] is IdentifierNode targetNode) {
			targetName = targetNode.Name;
		} else if (node.Arguments[0] is NumberLiteralNode numNode) {
			targetName = numNode.Value.ToString();
		} else {
			_errors.Add(new SemanticError(
				".target directive requires an identifier or numeric CPU name (e.g., nes, 6502, 65816)",
				node.Location));
			return;
		}

		var target = Arch.TargetResolver.Resolve(targetName);

		if (target is null) {
			_errors.Add(new SemanticError(
				$"Unknown target architecture: {targetName}",
				node.Location));
			return;
		}

		SetTarget(target.Value, node);
	}

	/// <summary>
	/// Sets the target architecture.
	/// </summary>
	private void SetTarget(TargetArchitecture target, DirectiveNode node) {
		// Allow setting to the same value (idempotent)
		if (_targetSetFromSource && Target != target) {
			_errors.Add(new SemanticError(
				"Target architecture already set - cannot change",
				node.Location));
			return;
		}

		Target = target;
		_targetSetFromSource = true;
		_profile = TargetResolver.TryGetProfile(target);
		ProcessorState = _profile?.CreateProcessorState();
	}

	/// <summary>
	/// Handles .assert directive for compile-time assertions.
	/// </summary>
	private void HandleAssertDirective(DirectiveNode node) {
		// Assertions are checked in pass 2 after all symbols are defined
		if (_pass != 2) return;

		if (node.Arguments.Count < 1) {
			_errors.Add(new SemanticError(
				".assert directive requires a condition expression",
				node.Location));
			return;
		}

		// Evaluate the assertion condition
		var condition = EvaluateExpression(node.Arguments[0]);
		if (condition is null) {
			_errors.Add(new SemanticError(
				".assert condition could not be evaluated",
				node.Location));
			return;
		}

		// Check if assertion passes
		if (condition == 0) {
			// Get optional message
			string message = "Assertion failed";
			if (node.Arguments.Count >= 2 && node.Arguments[1] is StringLiteralNode strNode) {
				message = strNode.Value;
			}

			_errors.Add(new SemanticError(message, node.Location));
		}
	}

	/// <summary>
	/// Handles .error directive for unconditional errors.
	/// </summary>
	private void HandleErrorDirective(DirectiveNode node) {
		if (_pass != 1) return;

		string message = "Error directive";
		if (node.Arguments.Count >= 1 && node.Arguments[0] is StringLiteralNode strNode) {
			message = strNode.Value;
		}

		_errors.Add(new SemanticError(message, node.Location));
	}

	/// <summary>
	/// Handles .warning directive for unconditional warnings.
	/// </summary>
	private void HandleWarningDirective(DirectiveNode node) {
		if (_pass != 1) return;

		string message = "Warning";
		if (node.Arguments.Count >= 1 && node.Arguments[0] is StringLiteralNode strNode) {
			message = strNode.Value;
		}

		// For now, treat warnings as errors (could add separate warning list later)
		_errors.Add(new SemanticError($"Warning: {message}", node.Location));
	}

	// ========================================================================
	// Expression Evaluation
	// ========================================================================

	/// <summary>
	/// Attempts to evaluate an expression to a constant value.
	/// </summary>
	/// <param name="expr">The expression to evaluate.</param>
	/// <returns>The value, or null if not evaluable.</returns>
	public long? EvaluateExpression(ExpressionNode expr) {
		return expr switch {
			NumberLiteralNode num => num.Value,
			IdentifierNode id => EvaluateIdentifier(id),
			BinaryExpressionNode bin => EvaluateBinary(bin),
			UnaryExpressionNode un => EvaluateUnary(un),
			_ => null
		};
	}

	/// <summary>
	/// Evaluates an identifier reference.
	/// </summary>
	private long? EvaluateIdentifier(IdentifierNode node) {
		// Special identifiers
		if (node.Name == "*" || node.Name == "$") {
			return CurrentAddress;
		}

		// Anonymous label references (+ or -)
		if (IsAnonymousLabelName(node.Name)) {
			bool isForward = node.Name[0] == '+';
			int count = node.Name.Length;
			return SymbolTable.ResolveAnonymousLabel(isForward, count, CurrentAddress, node.Location);
		}

		// Named anonymous label references (+name or -name)
		if (IsNamedAnonymousLabelName(node.Name)) {
			return SymbolTable.ResolveNamedAnonymousLabel(node.Name, CurrentAddress, node.Location);
		}

		if (SymbolTable.TryGetSymbol(node.Name, out var symbol) && symbol?.Value.HasValue == true) {
			return symbol.Value;
		}

		return null;
	}

	/// <summary>
	/// Evaluates a binary expression.
	/// </summary>
	private long? EvaluateBinary(BinaryExpressionNode node) {
		var left = EvaluateExpression(node.Left);
		var right = EvaluateExpression(node.Right);

		if (!left.HasValue || !right.HasValue) {
			return null;
		}

		return node.Operator switch {
			BinaryOperator.Add => left.Value + right.Value,
			BinaryOperator.Subtract => left.Value - right.Value,
			BinaryOperator.Multiply => left.Value * right.Value,
			BinaryOperator.Divide => right.Value != 0 ? left.Value / right.Value : null,
			BinaryOperator.Modulo => right.Value != 0 ? left.Value % right.Value : null,
			BinaryOperator.BitwiseAnd => left.Value & right.Value,
			BinaryOperator.BitwiseOr => left.Value | right.Value,
			BinaryOperator.BitwiseXor => left.Value ^ right.Value,
			BinaryOperator.LeftShift => left.Value << (int)right.Value,
			BinaryOperator.RightShift => left.Value >> (int)right.Value,
			BinaryOperator.Equal => left.Value == right.Value ? 1 : 0,
			BinaryOperator.NotEqual => left.Value != right.Value ? 1 : 0,
			BinaryOperator.LessThan => left.Value < right.Value ? 1 : 0,
			BinaryOperator.GreaterThan => left.Value > right.Value ? 1 : 0,
			BinaryOperator.LessOrEqual => left.Value <= right.Value ? 1 : 0,
			BinaryOperator.GreaterOrEqual => left.Value >= right.Value ? 1 : 0,
			BinaryOperator.LogicalAnd => (left.Value != 0 && right.Value != 0) ? 1 : 0,
			BinaryOperator.LogicalOr => (left.Value != 0 || right.Value != 0) ? 1 : 0,
			_ => null
		};
	}

	/// <summary>
	/// Evaluates a unary expression.
	/// </summary>
	private long? EvaluateUnary(UnaryExpressionNode node) {
		var operand = EvaluateExpression(node.Operand);

		if (!operand.HasValue) {
			return null;
		}

		return node.Operator switch {
			UnaryOperator.Negate => -operand.Value,
			UnaryOperator.BitwiseNot => ~operand.Value,
			UnaryOperator.LogicalNot => operand.Value == 0 ? 1 : 0,
			UnaryOperator.LowByte => operand.Value & 0xff,
			UnaryOperator.HighByte => (operand.Value >> 8) & 0xff,
			UnaryOperator.BankByte => (ApplySymbolBankForUnary(node.Operand, operand.Value) >> 16) & 0xff,
			_ => null
		};
	}

	/// <summary>
	/// Folds a referenced symbol's bank into a 16-bit value to form a 24-bit
	/// banked address, for `^` (bank-byte) evaluation.
	///
	/// Without this, `^(Label)` on a label defined under a non-zero `.bank`
	/// always evaluated to 0: EvaluateIdentifier only returns Symbol.Value (a
	/// plain 16-bit address) -- the bank lives in the separate Symbol.Bank
	/// field (see Symbol.cs) and was never consulted here, even though
	/// CodeGenerator's own ApplySymbolBank (used for jsl/.long operands) has
	/// done exactly this fold since cross-bank references were fixed. `^`
	/// was the one reference form that pass didn't cover.
	/// </summary>
	private long ApplySymbolBankForUnary(ExpressionNode operandNode, long value) {
		if (value >= 0 && value <= 0xffff
			&& operandNode is IdentifierNode idNode
			&& SymbolTable.TryGetSymbol(idNode.Name, out var symbol)
			&& symbol is { Bank: >= 0 }) {
			return value | ((long)symbol.Bank << 16);
		}

		return value;
	}

	// ========================================================================
	// Instruction Size Calculation
	// ========================================================================

	/// <summary>
	/// Calculates the size of an instruction in bytes.
	/// </summary>
	private int GetInstructionSize(InstructionNode node, AddressingMode effectiveMode) {
		// Branch instructions are always 2 bytes (opcode + relative offset)
		var mnemonic = node.Mnemonic;
		if (mnemonic.Length > 2 && mnemonic[^2] == '.') {
			mnemonic = mnemonic[..^2];
		}

		// Architecture-specific instruction sizing
		var sizeProfile = Arch.TargetResolver.TryGetProfile(Target);
		if (sizeProfile is not null) {
			var operandId = node.Operand is IdentifierNode idn ? idn.Name : null;

			// Build additional operand info for multi-operand architectures
			List<ResolvedOperand>? additionalOperands = null;
			if (node.Operands.Count > 1) {
				additionalOperands = new List<ResolvedOperand>(node.Operands.Count - 1);
				for (int i = 1; i < node.Operands.Count; i++) {
					var addlOp = node.Operands[i];
					string? addlId;
					long? addlValue;

					if (TryResolveShiftedRegisterOperand(addlOp, out var shiftedReg, out var shiftAmount, out var shiftOperator, out var isNegative, out var shiftRegisterName)) {
						addlId = shiftedReg;
						addlValue = shiftRegisterName is null ? shiftAmount : null;
						additionalOperands.Add(new ResolvedOperand(addlId, addlValue, shiftOperator, isNegative, shiftRegisterName));
						continue;
					} else {
						addlId = addlOp is IdentifierNode idn2 ? idn2.Name : null;
						addlValue = TryGetConstantOperandValue(addlOp);
					}

					additionalOperands.Add(new ResolvedOperand(addlId, addlValue));
				}
			}

			var specialSize = sizeProfile.Encoder.GetSpecialInstructionSize(
				mnemonic, operandId, node.Operand is not null, node.SizeSuffix, additionalOperands);
			if (specialSize > 0) {
				return specialSize;
			}
		}

		if (IsLongBranchInstruction(mnemonic)) {
			return 3; // opcode + 2 byte relative offset
		}

		if (IsBranchInstruction(mnemonic)) {
			return 2; // opcode + 1 byte relative offset
		}

		// Use the encoding table size when the addressing mode is unambiguous.
		// This handles 65816 mnemonics whose operand size differs from the mode's
		// usual size (e.g., jml/jsl encode 3 operand bytes even in Absolute mode).
		if (Target == TargetArchitecture.WDC65816
			&& node.SizeSuffix is null
			&& effectiveMode != AddressingMode.Immediate
			&& sizeProfile is not null
			&& sizeProfile.Encoder.TryEncode(mnemonic, effectiveMode, out var fixedEncoding)) {
			return fixedEncoding.Size;
		}

		// Base opcode is 1 byte
		int size = 1;

		// Add operand size based on effective addressing mode
		size += GetOperandSize(effectiveMode, node.SizeSuffix, mnemonic);

		return size;
	}

	/// <summary>
	/// Tries to get a constant value from an operand expression without side effects.
	/// Only returns a value for numeric literals and simple constant expressions
	/// (EQU-defined constants and arithmetic on them). Does not resolve labels or
	/// anonymous references.
	/// </summary>
	private long? TryGetConstantOperandValue(ExpressionNode operand) {
		if (operand is NumberLiteralNode num) {
			return num.Value;
		}

		// Resolve EQU-defined constants (not address labels)
		if (operand is IdentifierNode ident &&
			SymbolTable.TryGetSymbol(ident.Name, out var symbol) &&
			symbol is not null && symbol.IsDefined &&
			symbol.Type == SymbolType.Constant && symbol.Value.HasValue) {
			return symbol.Value.Value;
		}

		// Constant-only unary expressions (e.g. -CONST, >CONST, ^CONST).
		// Kept parallel with EvaluateUnary, but never resolves labels.
		if (operand is UnaryExpressionNode unary) {
			var unaryValue = TryGetConstantOperandValue(unary.Operand);
			if (!unaryValue.HasValue) return null;
			return unary.Operator switch {
				UnaryOperator.Negate => -unaryValue.Value,
				UnaryOperator.BitwiseNot => ~unaryValue.Value,
				UnaryOperator.LogicalNot => unaryValue.Value == 0 ? 1 : 0,
				UnaryOperator.LowByte => unaryValue.Value & 0xff,
				UnaryOperator.HighByte => (unaryValue.Value >> 8) & 0xff,
				UnaryOperator.BankByte => (unaryValue.Value >> 16) & 0xff,
				_ => null
			};
		}

		// Constant-only binary expressions (e.g. CONST+1, CONST*2). Without this,
		// the layout pass sizes e.g. "lda CONST+1" as Absolute (3 bytes) while the
		// code generator optimizes it to ZeroPage (2 bytes), so every later label
		// and .word reference drifts by one byte per occurrence (issue #376).
		if (operand is BinaryExpressionNode binary) {
			var left = TryGetConstantOperandValue(binary.Left);
			var right = TryGetConstantOperandValue(binary.Right);
			if (!left.HasValue || !right.HasValue) return null;
			return binary.Operator switch {
				BinaryOperator.Add => left.Value + right.Value,
				BinaryOperator.Subtract => left.Value - right.Value,
				BinaryOperator.Multiply => left.Value * right.Value,
				BinaryOperator.Divide => right.Value != 0 ? left.Value / right.Value : null,
				BinaryOperator.Modulo => right.Value != 0 ? left.Value % right.Value : null,
				BinaryOperator.BitwiseAnd => left.Value & right.Value,
				BinaryOperator.BitwiseOr => left.Value | right.Value,
				BinaryOperator.BitwiseXor => left.Value ^ right.Value,
				BinaryOperator.LeftShift => left.Value << (int)right.Value,
				BinaryOperator.RightShift => left.Value >> (int)right.Value,
				BinaryOperator.Equal => left.Value == right.Value ? 1 : 0,
				BinaryOperator.NotEqual => left.Value != right.Value ? 1 : 0,
				BinaryOperator.LessThan => left.Value < right.Value ? 1 : 0,
				BinaryOperator.GreaterThan => left.Value > right.Value ? 1 : 0,
				BinaryOperator.LessOrEqual => left.Value <= right.Value ? 1 : 0,
				BinaryOperator.GreaterOrEqual => left.Value >= right.Value ? 1 : 0,
				BinaryOperator.LogicalAnd => (left.Value != 0 && right.Value != 0) ? 1 : 0,
				BinaryOperator.LogicalOr => (left.Value != 0 || right.Value != 0) ? 1 : 0,
				_ => null
			};
		}

		return null;
	}

	private static bool TryResolveShiftedRegisterOperand(ExpressionNode operand, out string registerName, out long shiftAmount, out string? shiftOperator, out bool isNegative, out string? shiftRegisterName) {
		registerName = string.Empty;
		shiftAmount = 0;
		shiftOperator = null;
		isNegative = false;
		shiftRegisterName = null;

		ExpressionNode registerOperand = operand;
		if (operand is BinaryExpressionNode {
			Left: var left,
			Right: var rightOperand
		} shiftExpr) {
			shiftOperator = shiftExpr.Operator switch {
				BinaryOperator.LeftShift => "lsl",
				BinaryOperator.RightShift => "lsr",
				BinaryOperator.Divide => "asr",
				BinaryOperator.BitwiseOr => "ror",
				BinaryOperator.Modulo => "rrx",
				_ => null
			};

			if (shiftOperator is null) {
				return false;
			}

			registerOperand = left;
			if (rightOperand is NumberLiteralNode rightNumber) {
				shiftAmount = rightNumber.Value;
			} else if (rightOperand is IdentifierNode rightIdentifier) {
				shiftRegisterName = rightIdentifier.Name;
			} else {
				return false;
			}
		}

		if (registerOperand is UnaryExpressionNode {
			Operator: UnaryOperator.Negate,
			Operand: IdentifierNode negatedIdentifier
		}) {
			isNegative = true;
			registerName = negatedIdentifier.Name;
			return true;
		}

		if (registerOperand is IdentifierNode identifier) {
			registerName = identifier.Name;
			return true;
		}

		return false;
	}

	/// <summary>
	/// Resolves the effective addressing mode for instruction sizing, mirroring
	/// the code generator's Absolute→ZeroPage optimization so label addresses
	/// are consistent between analyzer and code generator.
	/// </summary>
	private AddressingMode ResolveEffectiveSizingMode(string mnemonic, AddressingMode mode, long value) {
		// Strip size suffix for instruction lookup
		var lower = mnemonic.ToLowerInvariant();
		if (lower.Length > 2 && lower[^2] == '.') {
			lower = lower[..^2];
		}

		// Canonicalize parser (addr,x) form for instructions that only support
		// absolute indexed-indirect and not indexed-indirect.
		if (mode == AddressingMode.IndexedIndirect
			&& !SupportsAddressingMode(lower, AddressingMode.IndexedIndirect)
			&& SupportsAddressingMode(lower, AddressingMode.AbsoluteIndexedIndirect)) {
			return AddressingMode.AbsoluteIndexedIndirect;
		}

		// Branch instructions: Absolute → Relative (already handled by IsBranchInstruction)
		if (IsBranchInstruction(lower)) {
			return mode;
		}

		// Upgrade Absolute → AbsoluteLong when value exceeds 16-bit range
		if (value > 0xffff) {
			return mode switch {
				AddressingMode.Absolute when SupportsAddressingMode(lower, AddressingMode.AbsoluteLong) => AddressingMode.AbsoluteLong,
				AddressingMode.AbsoluteX when SupportsAddressingMode(lower, AddressingMode.AbsoluteLongX) => AddressingMode.AbsoluteLongX,
				_ => mode
			};
		}

		// Downgrade Absolute → ZeroPage when value fits in 8 bits
		var isZeroPage = value >= 0 && value <= 0xff;
		if (!isZeroPage) {
			return mode;
		}

		return mode switch {
			AddressingMode.Absolute when SupportsAddressingMode(lower, AddressingMode.ZeroPage) => AddressingMode.ZeroPage,
			AddressingMode.AbsoluteX when SupportsAddressingMode(lower, AddressingMode.ZeroPageX) => AddressingMode.ZeroPageX,
			AddressingMode.AbsoluteY when SupportsAddressingMode(lower, AddressingMode.ZeroPageY) => AddressingMode.ZeroPageY,
			AddressingMode.Indirect when SupportsAddressingMode(lower, AddressingMode.ZeroPageIndirect) => AddressingMode.ZeroPageIndirect,
			_ => mode
		};
	}

	/// <summary>
	/// Checks whether the current target architecture supports a given addressing mode
	/// for the specified instruction mnemonic.
	/// </summary>
	private bool SupportsAddressingMode(string mnemonic, AddressingMode mode) {
		var profile = Arch.TargetResolver.TryGetProfile(Target);
		if (profile is null) return false;
		return profile.Encoder.TryEncode(mnemonic, mode, out _);
	}

	/// <summary>
	/// Gets the operand size for an addressing mode.
	/// </summary>
	private int GetOperandSize(AddressingMode mode, char? sizeSuffix, string? mnemonic = null) {
		// Size suffix overrides
		if (sizeSuffix.HasValue) {
			return sizeSuffix.Value switch {
				'b' => 1,
				'w' => 2,
				'l' => 3,
				_ => 0
			};
		}

		// For 65816 immediate mode, size depends on M/X flags and instruction
		if (Target == TargetArchitecture.WDC65816 && mode == AddressingMode.Immediate && mnemonic != null) {
			var accumulatorIs16Bit = ProcessorState?.AccumulatorIs16Bit ?? false;
			var indexIs16Bit = ProcessorState?.IndexIs16Bit ?? false;
			var lower = mnemonic.ToLowerInvariant();
			// Index register instructions use X flag
			if (lower is "ldx" or "ldy" or "cpx" or "cpy") {
				return indexIs16Bit ? 2 : 1; // 2 bytes in 16-bit, 1 byte in 8-bit
			}
			// Accumulator instructions use M flag
			if (lower is "lda" or "adc" or "sbc" or "cmp" or "and" or "ora" or "eor" or "bit") {
				return accumulatorIs16Bit ? 2 : 1; // 2 bytes in 16-bit, 1 byte in 8-bit
			}
			// REP/SEP are always 8-bit immediate
			if (lower is "rep" or "sep") {
				return 1;
			}
			// PEA is always 16-bit
			if (lower is "pea") {
				return 2;
			}
			// Default to current accumulator size for other immediate instructions
			return accumulatorIs16Bit ? 2 : 1;
		}

		return mode switch {
			AddressingMode.Implied => 0,
			AddressingMode.Accumulator => 0,
			AddressingMode.Immediate => 1, // 6502/SM83: always 1 byte immediate
			AddressingMode.ZeroPage => 1,
			AddressingMode.ZeroPageX => 1,
			AddressingMode.ZeroPageY => 1,
			AddressingMode.Absolute => 2,
			AddressingMode.AbsoluteX => 2,
			AddressingMode.AbsoluteY => 2,
			AddressingMode.Indirect => 2,
			AddressingMode.IndexedIndirect => 1,
			AddressingMode.IndirectIndexed => 1,
			AddressingMode.Relative => 1,
			AddressingMode.AbsoluteLong => 3,
			AddressingMode.AbsoluteLongX => 3,
			AddressingMode.StackRelative => 1,
			AddressingMode.StackRelativeIndirectIndexed => 1,
			AddressingMode.DirectPageIndirectLong => 1,
			AddressingMode.DirectPageIndirectLongY => 1,
			AddressingMode.AbsoluteIndirectLong => 2,
			AddressingMode.AbsoluteIndexedIndirect => 2,
			AddressingMode.BlockMove => 2,
			AddressingMode.MemoryReference => 0, // GB-specific, varies
			_ => 0
		};
	}
}

/// <summary>
/// Lynx header and boot code configuration settings.
/// </summary>
/// <param name="GameName">Cart name (up to 32 characters).</param>
/// <param name="Manufacturer">Manufacturer name (up to 16 characters).</param>
/// <param name="Rotation">Screen rotation mode.</param>
/// <param name="Bank0Size">ROM bank 0 size in bytes.</param>
/// <param name="Bank1Size">ROM bank 1 size in bytes (0 for single-bank).</param>
/// <param name="EntryPoint">Entry point address after boot code execution.</param>
/// <param name="UseBootCode">Whether to generate standard boot code.</param>
public sealed record LynxSettings(
	string GameName,
	string Manufacturer,
	CodeGen.LynxRotation Rotation,
	int Bank0Size,
	int Bank1Size,
	int EntryPoint,
	bool UseBootCode
);
